name: Build macOS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: brew install wget cdrtools dmg2img
      
      - name: Download macOS
        run: softwareupdate --fetch-full-installer --full-installer-version 15
      
      - name: Create RAM disk
        run: diskutil erasevolume HFS+ "ramdisk" $(hdiutil attach -nomount ram://16777216)
      
      - name: Create ISO
        run: |
          sudo /Applications/Install\ macOS\ Sequoia.app/Contents/Resources/createinstallmedia --volume /Volumes/ramdisk --nointeraction
          hdiutil create -o /tmp/macOS.iso -source /Volumes/ramdisk -format UDTO
          mv /tmp/macOS.iso.cdr /tmp/macOS.iso
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: macOS_Sequoia_15.iso
          path: /tmp/macOS.iso
